#ifndef __M_LANG_H__
#define __M_LANG_H__

enum LanguageContainer
{
    // ERROR
    ERROR,

    // Safe mode
    MESSAGE_SAFE_MODE_0,
    MESSAGE_SAFE_MODE_1,
    MESSAGE_SAFE_MODE_2,

    // Button string
    BUTTON_LEFT,
    BUTTON_UP,
    BUTTON_RIGHT,
    BUTTON_DOWN,
    BUTTON_CROSS,
    BUTTON_CIRCLE,
    BUTTON_SQUARE,
    BUTTON_TRIANGLE,
    BUTTON_L,
    BUTTON_R,
    BUTTON_L2,
    BUTTON_R2,
    BUTTON_L3,
    BUTTON_R3,
    BUTTON_SELECT,
    BUTTON_START,
    BUTTON_PSBUTTON,
    BUTTON_LEFT_ANALOG,
    BUTTON_LEFT_ANALOG_LEFT,
    BUTTON_LEFT_ANALOG_UP,
    BUTTON_LEFT_ANALOG_RIGHT,
    BUTTON_LEFT_ANALOG_DOWN,
    BUTTON_RIGHT_ANALOG,
    BUTTON_RIGHT_ANALOG_LEFT,
    BUTTON_RIGHT_ANALOG_UP,
    BUTTON_RIGHT_ANALOG_RIGHT,
    BUTTON_RIGHT_ANALOG_DOWN,
    BUTTON_AND,
    BUTTON_OR,

    // Button string 2
    BUTTON_A,
    BUTTON_B,
    BUTTON_C,
    BUTTON_D,
    BUTTON_E,
    BUTTON_F,
    BUTTON_G,
    BUTTON_H,
    BUTTON_X,
    BUTTON_Y,
    BUTTON_Z,

    BUTTON_X1,
    BUTTON_X2,
    BUTTON_X3,
    BUTTON_X4,
    BUTTON_Y1,
    BUTTON_Y2,
    BUTTON_Y3,
    BUTTON_Y4,

    SWICTH_MODE,
    COIN,
    SELECT,
    START,
    TURBO,

    // Browser
    PARENT_DIRECTORY,
    OPEN,
    EMU_SETTING,
    ABOUT,
    CHANGE_DIRECTORY,
    BACK_TO_BROWSER,

    // Setting tab
    TAB_MAIN,
    TAB_STATE,
    TAB_GRAPHICS,
    TAB_CONTROL,
    TAB_CORE,
    TAB_MISC,
    TAB_APP,

    // Menu general
    YES,
    NO,
    DISABLE,
    DEFAULT,
    AUTO,
    NONE,
    RESET_CONFIGS,

    // Menu main
    RESUME_GAME,
    RESET_GAME,
    EXIT_GAME,
    EXIT_TO_ARCH,
    EXIT_APP,

    // Menu grahics
    DISPLAY_SIZE,
    DISPLAY_RATIO,
    DISPLAY_ROTATE,
    GRAHICS_FILTERING,
    GRAHICS_SMOOTH,
    OVERLAY_SELECT,
    OVERLAY_MODE,
    SHOW_FPS,

    DISPLAY_SIZE_1X,
    DISPLAY_SIZE_2X,
    DISPLAY_SIZE_3X,
    DISPLAY_SIZE_FULL,

    DISPLAY_RATIO_DEFAULT,
    DISPLAY_RATIO_BY_GAME_RESOLUTION,
    DISPLAY_RATIO_BY_DEV_SCREEN,
    DISPLAY_RATIO_8_7,
    DISPLAY_RATIO_4_3,
    DISPLAY_RATIO_3_2,
    DISPLAY_RATIO_16_9,

    ROTATE_90,
    ROTATE_180,
    ROTATE_270,

    SHADER_LCD3X,
    SHADER_SHARP_SIMPLE,
    SHADER_SHARP,
    SHADER_AA,

    OVERLAY_MODE_OVERLAY,
    OVERLAY_MODE_BACKGROUND,

    // Menu control
    CTRL_PLAYER,
    FRONT_TOUCH_TO_PAD,
    BACK_TOUCH_TO_PAD,
    TURBO_DELAY,
    RESET_CTRL_CONFIGS_H,
    RESET_CTRL_CONFIGS_V,

    FOLLOW_DPAD,

    // Menu misc
    AUTO_STATE,
    DELETE_AUTO_STATE,
    SAVE_SCREENSHOT,
    SAVE_PREVIEW,

    // Menu app
    PREVIEW_PATH,
    PREVIEW_STYLE,
    APP_LOG,
    CORE_LOG,
    PRINT_LOG,
    LANGUAGE,

    FROM_AUTO_STATE,

    PRESERVE_FULL,
    STRETCH_FULL,

    // Menu state
    SAVESTATE_EXIST,
    SAVESTATE_NOEXIST,

    LOAD,
    SAVE,
    DELETE,
    CANCEL,

    LANGUAGE_CONTAINER_SIZE,
};

typedef struct LangEntry
{
    char *name;
    char **container;
} LangEntry;

extern LangEntry lang_entries[];
extern char **cur_lang;

int GetLangsLength();
int GetLangValue(int id);
int SetCurrentLang(int id);

#endif